services:
  frontend:
    ports:
      - "127.0.0.1:8080:80"

  backend:
    ports:
      - "127.0.0.1:3000:3000"

  minio:
    ports: []   # remove publicação

  postgres:
    ports: []   # remove publicação
